language: python
python:
- '2.7'
- '3.6'
env:
- DJANGO_VERSION=1.8
- DJANGO_VERSION=1.9
- DJANGO_VERSION=1.11
install:
- echo "0.01" > authz_group/VERSION
- pip install -e .
before_script:
- pip install coverage
- pip install python-coveralls
- pip install pycodestyle
- cp travis-ci/manage.py manage.py
- pip install Django==$DJANGO_VERSION
- python manage.py migrate
script:
- pycodestyle authz_group/ --exclude=migrations
- coverage run --source=authz_group/ manage.py test authz_group
after_script:
- coveralls
before_deploy:
- find authz_group/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > authz_group/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: FeGTi5RuxrwN9SO/XU9K8cDjOXQfw+nbddsprLadrmh3+ShzMml8UHQR6OlC5QCaoXJa7vi9c00lGHsNawdaM9S4CKoOE3znVVpvw9QdoU/KNkzt/vYulxipz8EzNOS99FNBpjlm96bYoCuae15I/btzeDZ8x9/Xv3lc7f+cxOg=
  on:
    tags: true
    python: '3.6'
    condition: 1.11 = $DJANGO_VERSION
